module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'scope-empty': [2, 'never'],
    'type-enum': [2, 'always', [
      'feat',
      'fix',
      'refactor',
      'test',
      'sim',
      'ci',
      'docs',
      'chore',
      'build',
    ]],
    'scope-enum': [2, 'always', [
      'arm',
      'amr',
      'humanoid',
      'sim',
      'nav',
      'slam',
      'perception',
      'control',
      'hw',
      'sdk',
      'infra',
      'docs',
      'ci',
      'repo',
    ]],
    'subject-max-length': [2, 'always', 72],
    'subject-case': [0],
  },
};
